# Generated by Django 3.2 on 2023-02-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='flavours',
        ),
        migrations.AddField(
            model_name='product',
            name='flavours',
            field=models.ManyToManyField(to='products.Flavour'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='strength',
        ),
        migrations.AddField(
            model_name='product',
            name='strength',
            field=models.ManyToManyField(to='products.Strength'),
        ),
    ]
