# Generated by Django 3.2 on 2023-03-09 15:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavour',
            fields=[
                ('flavour_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('flavour', models.CharField(blank=True, max_length=254, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('strength_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('strength', models.CharField(blank=True, max_length=254, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
