# Generated by Django 3.2 on 2023-02-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230220_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='elfar-600'),
            preserve_default=False,
        ),
    ]
