# Generated by Django 3.2 on 2023-02-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_home',
            field=models.BooleanField(blank=True, default=True),
            preserve_default=False,
        ),
    ]
